
services:
  backend:
    image: ubuntu:22.04
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yuasa-server
    volumes:
      - .:/workspace
      - /media/george/SSD-PUTA/y-recovery/data:/workspace/data
      - ./results:/workspace/data/results
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true  # Keep STDIN open even if not attached
    tty: true  # Allocate a pseudo-TTY